"""auto update

Revision ID: c1d977b04c46
Revises: 
Create Date: 2026-05-10 02:05:04.786419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d977b04c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betsmarts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codice', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betsmarts_id'), 'betsmarts', ['id'], unique=False)
    op.create_table('cashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cash_type', sa.String(), nullable=False),
    sa.Column('saldo_teorico', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_operator_id', sa.String(), nullable=True),
    sa.Column('current_shift_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_physical_balance', sa.Float(), nullable=True),
    sa.Column('last_operator_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashes_id'), 'cashes', ['id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('cash_name', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('saldo_teorico', sa.Float(), nullable=False),
    sa.Column('saldo_fisico', sa.Float(), nullable=False),
    sa.Column('differenza', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verificato_da', sa.String(), nullable=True),
    sa.Column('verificato_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_id'), 'discrepancies', ['id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('tipo_movimento', sa.String(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('cassa_origine_id', sa.Integer(), nullable=True),
    sa.Column('cassa_destinazione_id', sa.Integer(), nullable=True),
    sa.Column('saldo_origine_prima', sa.Float(), nullable=True),
    sa.Column('saldo_origine_dopo', sa.Float(), nullable=True),
    sa.Column('saldo_destinazione_prima', sa.Float(), nullable=True),
    sa.Column('saldo_destinazione_dopo', sa.Float(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('vlt_id', sa.Integer(), nullable=True),
    sa.Column('betsmart_id', sa.Integer(), nullable=True),
    sa.Column('causale', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('riferimento_movimento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('cash_name', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saldo_teorico_apertura', sa.Float(), nullable=True),
    sa.Column('saldo_fisico_apertura', sa.Float(), nullable=True),
    sa.Column('discrepanza_apertura', sa.Float(), nullable=True),
    sa.Column('note_apertura', sa.String(), nullable=True),
    sa.Column('saldo_teorico_chiusura', sa.Float(), nullable=True),
    sa.Column('saldo_fisico_chiusura', sa.Float(), nullable=True),
    sa.Column('discrepanza_chiusura', sa.Float(), nullable=True),
    sa.Column('note_chiusura', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('totale_incassi', sa.Float(), nullable=True),
    sa.Column('totale_pagamenti', sa.Float(), nullable=True),
    sa.Column('totale_sovvenzioni', sa.Float(), nullable=True),
    sa.Column('totale_restituzioni', sa.Float(), nullable=True),
    sa.Column('totale_svuotamenti', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cognome', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('ruolo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('vlts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codice', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlts_id'), 'vlts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlts_id'), table_name='vlts')
    op.drop_table('vlts')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_discrepancies_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_cashes_id'), table_name='cashes')
    op.drop_table('cashes')
    op.drop_index(op.f('ix_betsmarts_id'), table_name='betsmarts')
    op.drop_table('betsmarts')
    # ### end Alembic commands ###